sudo: required
language: cpp

addons:
  apt:
    packages:
      - cmake
    update: true

compiler:
  - clang

install:
  - mkdir build && cd build && cmake .. && make

script:
  - ./tests/BigFloat_test

notifications:
  email:
    on_failure: change
    on_success: never
